export const authConstants = {
    GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
    GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
    GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_INITIAL: "REGISTER_INITIAL",

    FIND_REQUEST: "FIND_REQUEST",
    FIND_SUCCESS: "FIND_SUCCESS",
    FIND_FAILURE: "FIND_FAILURE",

    RESET_REQUEST: "RESET_REQUEST",
    RESET_SUCCESS: "RESET_SUCCESS",
    RESET_FAILURE: "RESET_FAILURE",
    RESET_INITIAL: "RESET_INITIAL",

    LOG_OUT: "LOG_OUT",

    CHANGE_PASS_REQUEST: "CHANGE_PASS_REQUEST",
    CHANGE_PASS_SUCCESS: "CHANGE_PASS_SUCCESS",
    CHANGE_PASS_FAIL: "CHANGE_PASS_FAIL",
}