version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    env_file:
      - ../docker/postgres/pg.env
    ports:
      - '5432:5432'
    volumes:
      - ../docker/postgres/fs:/var/lib/postgresql/data/
    container_name: pg_13