create table tbl_user
(
    id                     bigint generated by default as identity
        constraint tbl_user_pkey
            primary key,
    created_by             varchar(255)                        not null,
    created_at             timestamp default CURRENT_TIMESTAMP not null,
    updated_by             varchar(255)                        not null,
    updated_at             timestamp default CURRENT_TIMESTAMP not null,
    avatar_url             varchar(255),
    bio                    varchar(255),
    birthdate              date,
    user_email             varchar(255)                        not null
        constraint uk_cid87yfpmi3no4sci7uk3srmy
            unique,
    enabled                boolean,
    language               varchar(255),
    location               varchar(255),
    locked                 boolean,
    name                   varchar(255),
    origin                 varchar(255),
    password               varchar(255)                        not null,
    profile_background_url varchar(255),
    provider_id            varchar(255),
    role                   varchar(255),
    surname                varchar(255),
    title_img_url          varchar(255),
    website                varchar(255)
);

create table chats
(
    id           bigint generated by default as identity
        constraint chats_pkey
            primary key,
    created_by   varchar(255)                        not null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    updated_by   varchar(255)                        not null,
    updated_at   timestamp default CURRENT_TIMESTAMP not null,
    initiator_id bigint
);

create table messages
(
    id         bigint generated by default as identity
        constraint messages_pkey
            primary key,
    created_by varchar(255)                        not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_by varchar(255)                        not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null,
    msg_body   varchar(255)
);

create table conn_chat_message
(
    chat_id    bigint
        constraint fkq51lymqtwslnh8nf93fttft2y
            references chats,
    message_id bigint not null
        constraint conn_chat_message_pkey
            primary key
        constraint fkq68as7cwnhfij5t9qd9na2sdv
            references messages
);

create table conn_user_message
(
    user_id    bigint
        constraint fksp2qkd6yjqvgh7w16s6iuo4s8
            references tbl_user,
    message_id bigint not null
        constraint conn_user_message_pkey
            primary key
        constraint fko7pmp024ci6mljqxk0t1fjo88
            references messages
);

create table conn_chat_user
(
    chat_id bigint not null
        constraint fks39w7hld207ht8mgu0mhq601h
            references chats,
    user_id bigint not null
        constraint fk45pe732xdlmwu49l65h606m2t
            references tbl_user,
    constraint conn_chat_user_pkey
        primary key (chat_id, user_id)
);

create table post
(
    id           bigint generated by default as identity
        constraint post_pkey
            primary key,
    created_by   varchar(255)                        not null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    updated_by   varchar(255)                        not null,
    updated_at   timestamp default CURRENT_TIMESTAMP not null,
    body         varchar(255),
    img_twit_url varchar(255),
    user_id      bigint                              not null
        constraint fk5or1f9qa18oxf39kdilu7np7g
            references tbl_user
);

create table tbl_repost
(
    id         bigint generated by default as identity
        constraint tbl_repost_pkey
            primary key,
    created_by varchar(255)                        not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_by varchar(255)                        not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null,
    body       varchar(255),
    post_id    bigint
        constraint fkq95rxtwy1xt6uh9miwo22shn
            references post,
    user_id    bigint
        constraint fkcx5xv3rvtsj3l2tt3ahjlayk6
            references tbl_user
);

create table comments
(
    id         bigint generated by default as identity
        constraint comments_pkey
            primary key,
    created_by varchar(255)                        not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_by varchar(255)                        not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null,
    body       varchar(255),
    post_id    bigint                              not null
        constraint comments_post_fk
            references post,
    user_id    bigint
        constraint fk6d6x64i4nwca1pn4ldve3e1si
            references tbl_user
);


create table posts_to_likes
(
    user_id bigint not null
        constraint fknivi26mq57nwduxpcu065aysu
            references tbl_user,
    post_id bigint not null
        constraint fk5643kethh6pgbje8qsbhxxpm2
            references post,
    constraint posts_to_likes_pkey
        primary key (user_id, post_id)
);

create table subscribers
(
    user_whom_id bigint not null
        constraint fkaivlhf9f7xchbe65raqmt9t3m
            references tbl_user,
    user_who_id  bigint not null
        constraint fkiog5lfllu91j91tf36fdutbbm
            references tbl_user,
    constraint subscribers_pkey
        primary key (user_who_id, user_whom_id)
);

create table confirmation_token
(
    id           bigint generated by default as identity
        constraint confirmation_token_pkey
            primary key,
    created_by   varchar(255)                        not null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    updated_by   varchar(255)                        not null,
    updated_at   timestamp default CURRENT_TIMESTAMP not null,
    confirmed_at timestamp,
    expires_at   timestamp                           not null,
    token        varchar(255)                        not null,
    user_id      bigint                              not null
        constraint fkr0jem314ddqj5atd6694na72m
            references tbl_user
);

create table tbl_refresh_tokens
(
    id         bigint generated by default as identity
        constraint tbl_refresh_tokens_pkey
            primary key,
    created_by varchar(255)                        not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_by varchar(255)                        not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null,
    token      varchar(255)
);

create table tbl_notification
(
    id           bigint generated by default as identity
        constraint tbl_notification_pkey
            primary key,
    created_by   varchar(255)                        not null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    updated_by   varchar(255)                        not null,
    updated_at   timestamp default CURRENT_TIMESTAMP not null,
    body         varchar(255),
    is_read      boolean,
    type         varchar(255),
    post_id      bigint
        constraint post_id_fk
            references post,
    submitter_id bigint                              not null
        constraint submitter_id_fk
            references tbl_user,
    user_id      bigint                              not null
        constraint user_id_fk
            references tbl_user
);
