export const postConstants = {
    ADD_NEW_POST : "ADD_NEW_POST",
    LOADING_POSTS : "LOADING_POSTS",
    UPDATE_POST : "UPDATE_POST",
    POST_IS_BEING_UPLOADED : "POST_IS_BEING_UPLOADED",
    RESET_POST :"RESET_POST",

    GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
    GET_ALL_POSTS_REQUEST: "GET_ALL_POSTS_REQUEST",
    GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",

    GET_USER_POSTS_SUCCESS: "GET_USER_POSTS_SUCCESS",
    GET_USER_POSTS_REQUEST: "GET_USER_POSTS_REQUEST",
    GET_USER_POSTS_FAILURE: "GET_USER_POSTS_FAILURE",

    CLEAR_POSTS: "CLEAR_POSTS"

}