export const NOTIFICATIONS_LOADING_INITIALIZE = 'NOTIFICATIONS_LOADING_INITIALIZE';
export const NOTIFICATIONS_LOADING_SUCCESS = 'NOTIFICATIONS_LOADING_SUCCESS';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';